# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi2.yaml
lint:
  extends:
    - minimal
  rules:
    no-unused-components: warning
referenceDocs:
  showConsole: false
